### ISSUE TITLE
[Header] Bouton vers la playlist ytube vidéos 2017 

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2017#107]
En lieu et place du bouton (das le header du site) qui mène vers la liste d'attente de la billetterie,
cela pourrait être mieux de rediriger vers la playlist youtube avec les vidéos de l'édition 2017 : 
https://www.youtube.com/playlist?list=PLuZ_sYdawLiWkhvpCuWV01mr1TO5etnvD&disable_polymer=true

**Comment by davinkevin** [comment]
Done, je m'occupe du reste demain ;)
