### ISSUE TITLE
Ajouter section vidéos 2017 sur la HP du site

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2017#108]
Les videosId sont mises pour chaque talk associé donc maintenant, afin de bien mettre en avant les vidéos de cette année, il faudrait rajouter une section sur la HP du site, du style :

Les vidéos de l'édition 2017 du DevFest Toulouse :

xxx

(a la DevFest Ukraine)

je voyais ça a la place de la fonctionnalité "featured videos". Je sais pas si tu vois ce que je veux dire.

**Comment by davinkevin** [comment]
Pour cela il faudrait quelque chose de la forme : 

```
{
      "speakers":"Jakub Škvára",
      "thumbnail":"/images/sessions/116.JPG",
      "title":"Polymer vs other libraries",
      "youtubeId":"-UEURYYVCmg"
    }
``` 
dans firebase, sous la clef `videos`.

L'on peut voir cela dans le fichier ici : 
https://github.com/GDGToulouse/site-devfest-toulouse-2017/blob/master/data/export-data-firebase.json#L2359

Je vais essayer de voir si je peux sortir cela facilement de Youtube...  Si tu as une autre idée, je suis preneur

**Comment by davinkevin** [comment]
Par contre, je n'ai pas gérer les "co-speakers", cela devenait trop galère et je pense qu'en terme d'espace, l'on était trop juste pour afficher ce type d'information.
