### ISSUE TITLE
Changer le lien de la carte

### ISSUE THREAD

**Issue by EmmanuelVinas** [GDGToulouse/site-devfest-toulouse-2017#33]
C'est mieux d'avoir la direction dans maps : 
 https://www.google.com/maps/dir//4+Impasse+Emile+Zola,+31700+Blagnac,+France

Actuellement il y a: 
https://www.google.com/maps/dir/43.644436,1.373449/@43.644436,1.373449,18z
Mais maps a pas l'air de comprendre le lien.

**Comment by davinkevin** [comment]
Côté web, le résultat est identique pour moi (il fait la conversion entre coordonnées Lat/lng et adresse)

**Comment by EmmanuelVinas** [comment]
![image](https://cloud.githubusercontent.com/assets/3410544/25698675/0a5da41a-30c0-11e7-9c46-d1a898b20b07.png)

Ok mais en fait c'est le to qui déconne. Ca peut etre ca aussi : 
https://www.google.com/maps/dir//43.644436,1.373449

**Comment by davinkevin** [comment]
@JulienDelRio a dit sur le slack : 
> Pour la map, il faut mettre le lien vers le CGR sur Maps : https://goo.gl/maps/ihbCaXeLYqz

Vous voulez donc que cela remplace le lien présent sur la flèche de direction (en rouge ci dessous) : 
<img width="665" alt="capture d ecran 2017-05-08 a 12 46 23" src="https://cloud.githubusercontent.com/assets/1970922/25801100/885be96a-33ec-11e7-9e94-d4cd90c4b4c9.png">

Entre ton message @EmmanuelVinas et celui de @JulienDelRio, je ne sais donc pas quoi faire 😉 

Pour info, la location fait parti du template avec une URL généré à partir des coordonnées : https://github.com/GDGToulouse/site-devfest-toulouse-2017/blob/5c19cd030ea64e1d2331235c45e6787b8aa175ab/src/elements/map-block.html#L157-L157

L'on peut le changer, mais cela va nécessiter de la hard-coder...

Donc, votre dernier mot, vous voulez quoi @EmmanuelVinas et @JulienDelRio ? 😄 

Je propose l'url suivante 
> https://www.google.fr/maps/dir//Cinéma+CGR+Blagnac,+ZAC+du+Grand+Noble,+2+Allée+Emile+Zola,+31700+Blagnac/@43.6442066,1.3722505,17.76z

qui génère le résultat suivant : 
![image](https://cloud.githubusercontent.com/assets/1970922/25801513/332f2194-33ee-11e7-8dff-63d117970a0e.png)

**Comment by davinkevin** [comment]
La PR est prête, donc il n'y a plus qu'à 😄

**Comment by juliendelrio** [comment]
Et il a confusion.

Moi je parle de rendre cliquable l'ensemble de la carte. @EmmanuelVinas parle juste du bouton itinéraire.

**Comment by davinkevin** [comment]
Ok, donc je merge cette PR pour @EmmanuelVinas et j'ouvre une nouvelle issue pour ta demande
