### ISSUE TITLE
fix(map): rendre toute la map cliquable

### ISSUE THREAD

**Issue by davinkevin** [GDGToulouse/site-devfest-toulouse-2017#42]
Suite au message de @JulienDelRio : 
> Et il a confusion.
>
>Moi je parle de rendre cliquable l'ensemble de la carte. @EmmanuelVinas parle juste du bouton itinéraire.

et sur slack : 
> Pour la map, il faut mettre le lien vers le CGR sur Maps : https://goo.gl/maps/ihbCaXeLYqz

Donc, tu souhaite que toute la partie map soit un lien ? Toute la zone en image ci dessous ?
![image](https://cloud.githubusercontent.com/assets/1970922/25803866/4e6811cc-33f9-11e7-970b-acc3f67f8ad6.png)

Je trouve pas cela super "pratique", surtout pour les IHM mobiles qui feront du swipe en cliquant dessus. 
De plus, étant donné la nature du dom, je ne sais pas si cela est possible

Avis ?

**Comment by scraly** [comment]
Même avis, sur mobile les utilisateurs vont faire du swipe dessus, certains feront un print screen sur pc et ne cliqueront pas du tout.
Si on a une foule de personnes qui nous disent que c'est vraiment inutilisable alors là on réfléchira mais je ne suis pas fan de modifier une feature de hoverboard en faisant un quick fix hardcodé de notre côté.

Mais plutôt fan pour modifier l'url lors du click si besoin :-).

**Comment by davinkevin** [comment]
Réponse de @JulienDelRio sur slack : 

> En fait il faudrait juste que la partie en bleue soit cliquable
![pasted_image_at_2017_05_08_15_14_480](https://cloud.githubusercontent.com/assets/1970922/25823471/7efeefde-343c-11e7-914e-ec3a4e86ac94.png)

@JulienDelRio poste ici directement la prochaine fois 😄
