### ISSUE TITLE
Mauvais format de date sur les articles de blogs

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2017#45]
Modifier le format de la date anglais => format de la date en français

**Comment by davinkevin** [comment]
(pas le temps de faire plus de test, je jette l'idée ici) : 

```
new Date(posted).toLocaleString('fr-FR', {month: 'short', day: 'numeric', year: 'numeric'} )
```
Cela donne : 
![image](https://cloud.githubusercontent.com/assets/1970922/25892641/4911c43e-3575-11e7-9c51-86ebb7102aa1.png)



Pour mettre à la ligne https://github.com/GDGToulouse/site-devfest-toulouse-2017/blob/master/src/pages/post-page.html#L252

La `local` et l'objet `{month: 'short', day: 'numeric', year: 'numeric'}` devrait être intégrer à la conf pour pouvoir faire une PR au projet Hoverboard
