### ISSUE TITLE
Mettre à jour suite au soldout

### ISSUE THREAD

**Issue by juliendelrio** [GDGToulouse/site-devfest-toulouse-2017#78]
Suite au sold out : 
- passer l'image des billets en sold out
- remplacer les textes "Acheter un billet" par "S'inscrire en attente"

**Comment by davinkevin** [comment]
Done in 57e5425cb5f1d17ad3c9d6baf704907863a1c0dc

**Comment by scraly** [comment]
La formulation du bouton "S'INSCRIRE EN ATTENTE" est très étrange sur le site.
Donc oui pour conserver le bouton car des billets vont être disponible qd des personnes revendent les leur mais ça serait top de changer la formulation :$.

**Comment by davinkevin** [comment]
Je mettrais "S'inscrire sur liste d'attente"... un avis @JulienDelRio @EmmanuelVinas @aaudevart ?

**Comment by scraly** [comment]
Ça risque de faire un bouton large mais c'est plus clair oui ! :+1:

**Comment by davinkevin** [comment]
Moi cela me choque pas tant que cela... 
![image](https://user-images.githubusercontent.com/1970922/29239134-4af195f2-7f46-11e7-9cf5-63d125528386.png)

@scraly @JulienDelRio @EmmanuelVinas @aaudevart, vos avis ?

**Comment by scraly** [comment]
👍 :-)
