### ISSUE TITLE
Rajouter Igor en speaker

### ISSUE THREAD

**Issue by scraly** [GDGToulouse/site-devfest-toulouse-2017#85]
Igor est le speaker de la 28ème conférence pour 2017 mais il n’apparaît pas sur le site.
Il faudrait le rajouter dans le json :-).

**Comment by davinkevin** [comment]
Bizarre, sachant que son talk est toujours présent 😄

**Comment by davinkevin** [comment]
Closes and Done in efd181f311c4ff1a54f013b673fb992ca79cc2fa
